# Generated by Django 2.0 on 2017-12-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='media/media/sf-extension.png', upload_to='media'),
        ),
    ]
