# Generated by Django 2.0 on 2017-12-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20171211_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='sf-extension.png', upload_to='sfs_images'),
        ),
    ]
