# Generated by Django 2.0 on 2017-12-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20171211_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='media/sf-extension.png', upload_to='book_images'),
        ),
    ]
