# Generated by Django 2.0 on 2018-01-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_book_copie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='copie',
            field=models.IntegerField(max_length=999),
        ),
    ]
