# Generated by Django 2.0 on 2018-01-09 23:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_auto_20180108_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdfs',
            field=models.FileField(default=django.utils.timezone.now, upload_to='pdfs'),
            preserve_default=False,
        ),
    ]
